name: ML Model CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        pip install -r requirements.txt

    - name: Train model
      run: |
        mkdir -p sample_images
        python src/train.py

    - name: Run tests
      run: |
        python src/test.py

    - name: Deploy model
      run: |
        python src/deploy.py

    - name: Save model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: deployed_models/

    - name: Save sample images
      uses: actions/upload-artifact@v4
      with:
        name: augmented-samples
        path: sample_images/
        if-no-files-found: error

    - name: Commit and push sample images
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add sample_images/
        git commit -m "Add augmented sample images [skip ci]" || echo "No changes to commit"
        git push origin ${GITHUB_REF#refs/heads/}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}